CREATE TABLE IF NOT EXISTS visits (
    id SERIAL PRIMARY KEY,
    visited_at TIMESTAMP NOT NULL
);

-- Add columns if they do not exist
ALTER TABLE visits ADD COLUMN IF NOT EXISTS hostname VARCHAR(255) DEFAULT 'unknown';
ALTER TABLE visits ADD COLUMN IF NOT EXISTS version VARCHAR(50) DEFAULT 'v1.0.0';

CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
